CREATE TABLE IF NOT EXISTS realestate.saved_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    area_slug TEXT NOT NULL REFERENCES realestate.neighbourhoods(slug) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_saved_areas UNIQUE (user_id, area_slug)
);

CREATE TABLE IF NOT EXISTS realestate.saved_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    search_name TEXT NOT NULL,
    filters_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS realestate.research_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    note_text TEXT NOT NULL,
    related_area_slug TEXT REFERENCES realestate.neighbourhoods(slug) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS realestate.comparison_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    area_slug_a TEXT NOT NULL REFERENCES realestate.neighbourhoods(slug) ON DELETE CASCADE,
    area_slug_b TEXT NOT NULL REFERENCES realestate.neighbourhoods(slug) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    report_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS realestate.analytics_metrics (
    metric_key TEXT PRIMARY KEY,
    metric_value NUMERIC,
    metric_context JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
