command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase_connection_string"
  - name: WEATHER_SOURCE_BASE_URL
    value: "https://api.weather.gov"
  - name: WEATHER_EMBEDDING_MODEL
    value: "sentence-transformers/all-MiniLM-L6-v2"
