CREATE TABLE IF NOT EXISTS ticket_category (
    ticket_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO ticket_category (category)
VALUES
    ('Access and Permission'),
    ('Device Request'),
    ('Inquiry'),
    ('Complaint'),
    ('Application Installation'),
    ('Technical Issue')
ON CONFLICT (category) DO NOTHING;
