CREATE TABLE IF NOT EXISTS ticket_status (
    ticket_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO ticket_status (status)
VALUES
    ('New'),
    ('In Progress'),
    ('Escalated'),
    ('Done'),
    ('Deleted')
ON CONFLICT (status) DO NOTHING;
