CREATE TABLE IF NOT EXISTS tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    ticket_category_id BIGINT NULL,
    ticket_status_id BIGINT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tickets_category
        FOREIGN KEY (ticket_category_id)
        REFERENCES ticket_category (ticket_category_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT fk_tickets_status
        FOREIGN KEY (ticket_status_id)
        REFERENCES ticket_status (ticket_status_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);
